{
 "title": "Grafana Downloads",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Download Count Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "SELECT (CAST(timestamp AS INTEGER) / 86400) * 86400 AS day, version, avg(downloads) from grafana\nWHERE timestamp > $__from / 1000 and timestamp <= $__to / 1000\nGROUP BY day, version\nORDER BY day ASC, version DESC;",
     "rawQueryText": "SELECT (CAST(timestamp AS INTEGER) / 86400) * 86400 AS day, version, avg(downloads) from grafana\nWHERE timestamp > $__from / 1000 and timestamp <= $__to / 1000\nGROUP BY day, version\nORDER BY day ASC, version DESC;",
     "timeColumns": [ "day" ]
    }
   ]
  },
  {
   "title": "Download Count Daily",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "WITH daily_data AS (\n    SELECT (CAST(timestamp AS INTEGER) / 86400) * 86400 AS day, version, avg(downloads) as downloads \n    FROM grafana\n    WHERE timestamp > $__from / 1000 and timestamp <= $__to / 1000\n    GROUP BY day, version\n)\nSELECT day, version, downloads - lag(downloads) over (PARTITION BY version ORDER BY day) as daily_downloads\nfrom daily_data\nORDER BY day ASC, version desc;",
     "rawQueryText": "WITH daily_data AS (\n    SELECT (CAST(timestamp AS INTEGER) / 86400) * 86400 AS day, version, avg(downloads) as downloads \n    FROM grafana\n    WHERE timestamp > $__from / 1000 and timestamp <= $__to / 1000\n    GROUP BY day, version\n)\nSELECT day, version, downloads - lag(downloads) over (PARTITION BY version ORDER BY day) as daily_downloads\nfrom daily_data\nORDER BY day ASC, version desc;",
     "timeColumns": [ "day" ]
    }
   ]
  },
  {
   "title": "Total Downloads",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "panelId": 3,
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latest Download Count Per Version",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "WITH ranked_daily_data AS (\n    SELECT\n        (CAST(timestamp AS INTEGER) / 86400) * 86400 AS day\n        , version\n        , avg(downloads) as downloads\n        , downloads - lead(downloads) over (PARTITION BY version ORDER BY timestamp DESC) as daily_downloads\n       , ROW_NUMBER() OVER (PARTITION BY version ORDER BY timestamp DESC) AS number\n    FROM grafana\n    WHERE timestamp > $__from / 1000\n    GROUP BY 1, version\n)\nSELECT day, version, downloads, daily_downloads\nFROM ranked_daily_data\nWHERE number =1\nORDER BY version DESC",
     "rawQueryText": "WITH ranked_daily_data AS (\n    SELECT\n        (CAST(timestamp AS INTEGER) / 86400) * 86400 AS day\n        , version\n        , avg(downloads) as downloads\n        , downloads - lead(downloads) over (PARTITION BY version ORDER BY timestamp DESC) as daily_downloads\n       , ROW_NUMBER() OVER (PARTITION BY version ORDER BY timestamp DESC) AS number\n    FROM grafana\n    WHERE timestamp > $__from / 1000\n    GROUP BY 1, version\n)\nSELECT day, version, downloads, daily_downloads\nFROM ranked_daily_data\nWHERE number =1\nORDER BY version DESC",
     "timeColumns": [ "day" ]
    }
   ]
  }
 ]
}