name: CI

on:
  push:
    branches:
      - "**"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - run: python -m pip install --upgrade pipenv
      
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      
      - run: pipenv install --deploy --dev
      
      - run: make test-linting
      - run: make test-unit
