name: CI

on:
  push:
    branches:
      - "**"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
  
      - run: make install-dependencies
          
      - run: make test
    